//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustumerOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustumerOrder()
        {
            this.OrderJobs = new HashSet<OrderJob>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int orderNumer { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> confirm { get; set; }
        public Nullable<int> status { get; set; }
        public int fk_UserID { get; set; }
    
        public virtual OrderConfirm OrderConfirm { get; set; }
        public virtual Userr Userr { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderJob> OrderJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
