//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHouse.Models
{
    using System.Data.SqlClient;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using WHouse.Models;

    public partial class CustumerOrder
    {
        private MydataEntities1 db = new MydataEntities1();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustumerOrder()
        {
            this.OrderJobs = new HashSet<OrderJob>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int orderNumer { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> confirm { get; set; }
        public Nullable<int> status { get; set; }
        public int fk_UserID { get; set; }
    
        public virtual OrderConfirm OrderConfirm { get; set; }
        public virtual Userr Userr { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderJob> OrderJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }


        public int UpdateOrderStatus(int id)
        {
            //Prieð  OCL naudojant turime turëti executing(kuris þymimas 1)
            CustumerOrder ord = db.CustumerOrders.Find(id);
            if (ord.confirm == 1)
            {
                string query = "UPDATE CustumerOrder SET confirm = '" + 3 + "', status ='" + 4 + "' WHERE ordernumer ='" + id + "'";
                // PO turime turëti confirm confirmed (kuris þymimas skaièiuku 3)
                SqlConnection connection = new SqlConnection(
                    @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Aurimas\Desktop\sandelis\sandelis\WHouse\WHouse\App_Data\Mydata.mdf;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework");
                connection.Open();
                SqlDataAdapter sda = new SqlDataAdapter(query, connection);
                sda.SelectCommand.ExecuteNonQuery();
                connection.Close();
                return 0;
            }
            else
            return 0;
        }


    }
}
