//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobWorker
    {
        public string posision { get; set; }
        public int id_JobWorker { get; set; }
        public int fk_OrderJobid_OrderJob { get; set; }
        public int fk_UserID { get; set; }
    
        public virtual Userr Userr { get; set; }
        public virtual OrderJob OrderJob { get; set; }
    }
}
