//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MydataEntities1 : DbContext
    {
        public MydataEntities1()
            : base("name=MydataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustumerOrder> CustumerOrders { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<IsBusy> IsBusies { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobWorker> JobWorkers { get; set; }
        public virtual DbSet<OrderConfirm> OrderConfirms { get; set; }
        public virtual DbSet<OrderJob> OrderJobs { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductToAdd> ProductToAdds { get; set; }
        public virtual DbSet<Rack> Racks { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Userr> Userrs { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<WarehouseAddition> WarehouseAdditions { get; set; }
    }
}
