//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderJob()
        {
            this.JobWorkers = new HashSet<JobWorker>();
        }
    
        public Nullable<System.DateTime> start { get; set; }
        public string place { get; set; }
        public Nullable<int> status { get; set; }
        public int id_OrderJob { get; set; }
        public int fk_JobworkNumer { get; set; }
        public int fk_WarehouseAdditionadditionNumer { get; set; }
        public int fk_CustumerOrderorderNumer { get; set; }
    
        public virtual CustumerOrder CustumerOrder { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobWorker> JobWorkers { get; set; }
        public virtual WarehouseAddition WarehouseAddition { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
