//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductToAdd
    {
        public Nullable<int> amount { get; set; }
        public int id_ProductToAdd { get; set; }
        public int fk_Inventoryproduct_numer { get; set; }
        public int fk_WarehouseAdditionadditionNumer { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual WarehouseAddition WarehouseAddition { get; set; }
    }
}
