//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseAddition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseAddition()
        {
            this.OrderJobs = new HashSet<OrderJob>();
            this.ProductToAdds = new HashSet<ProductToAdd>();
        }
    
        public int additionNumer { get; set; }
        public Nullable<int> confirm { get; set; }
        public int fk_UserID { get; set; }
    
        public virtual OrderConfirm OrderConfirm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderJob> OrderJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductToAdd> ProductToAdds { get; set; }
        public virtual Userr Userr { get; set; }
    }
}
